### ISSUE TITLE
Restart Server Glitch

### ISSUE THREAD

**Issue by jennocool** [CLADevs/Minion#11]
When i restart the server the minion is gone and idk why.

**Comment by eliassaliba12** [comment]
Must be an issue with the new dev cz that isnt happening to me

**Comment by xXNiceYT** [comment]
not sure please tell me how to reproduce it beacuse it doesn’t happen to me

**Comment by jaylac2000** [comment]
i get this [Server thread/CRITICAL]: InvalidStateException: "Entity is not registered" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 926
