### ISSUE TITLE
Wtf not spawn (2)

### ISSUE THREAD

**Issue by FahrizalNAH** [CLADevs/Minion#18]
Whyyy plugin error? Minion not spawn. do I have to use the api you use

**Comment by xXNiceYT** [comment]
Please provide us with the error

**Comment by xXNiceYT** [comment]
``

**Comment by FahrizalNAH** [comment]
it actually work when using command / minion. but when pressed to the ground it doesn't spawn

**Comment by FahrizalNAH** [comment]
Whyyy:'((

**Comment by xXNiceYT** [comment]
Bro idk not enough information

**Comment by xXNiceYT** [comment]
This issue will be fix on 1.13

**Comment by xXNiceYT** [comment]
This issue will be fix on 1.13

**Comment by xXNiceYT** [comment]
Issue should be solved!

**Comment by xXNiceYT** [comment]
Issue should be solved!
