### ISSUE TITLE
drops

### ISSUE THREAD

**Issue by thehexmor** [CLADevs/Minion#2]
do somethink to send blocks drop to chest , not the block

**Comment by xXNiceYT** [comment]
Huh please example more

**Comment by KadTheHunter** [comment]
So your saying you want the blocks that the minion mines, to be sent to a chest? How would that work? Set a chest coordinates in a config? @thehexmor

**Comment by xXNiceYT** [comment]
> So your saying you want the blocks that the minion mines, to be sent to a chest? How would that work? Set a chest coordinates in a config? @thehexmor

I can do that without using config but I don’t understand this guy is he talking about like linking Chest

**Comment by thehexmor** [comment]
i mean when minion mine diamond ore , you should send diamond to the chest not diamond ore ! :|

**Comment by thehexmor** [comment]
@xXNiceYT @LegoFan48737

**Comment by KadTheHunter** [comment]
Ahh, so when the Minion mines a Diamond Block, it should send the Diamond Block to a chest, instead of the Ore like it normally does.

**Comment by thehexmor** [comment]
yes . @LegoFan48737

**Comment by xXNiceYT** [comment]
I’ll do it when I got time
