### ISSUE TITLE
Minions despawning

### ISSUE THREAD

**Issue by XFactorLive2016** [CLADevs/Minion#20]
IDK how, but somehow random minions do despawn after server restart. Like every 5th restart a whole chunk gets minion cleared... I do use the minions at a world with void generator and without the world loading automatically after server restart.

**Comment by eforce67** [comment]
That might not be the plugins fault if your using a plugin that clears entity

**Comment by XFactorLive2016** [comment]
i have autoclearlagg but I flagges entity clear as false, maby I need to edit something in pocketmine.yml ?

**Comment by xXNiceYT** [comment]
Ya beacuse clear lag I’ll fix it tmr later
