### ISSUE TITLE
Adding Worlds for A SkyBlock server.

### ISSUE THREAD

**Issue by MattW1PE** [CLADevs/Minion#23]
How can I make it so it automatically adds the island worlds to allowed worlds in config? So I don’t add the SkyBlock island worlds manually.

**Comment by eliassaliba12** [comment]
In the config the option of the world is the list of worlds that minion can’t spawn in so only put the spawn/pvp/events(if available) and not the skyblock island name

**Comment by MattW1PE** [comment]
Ok thanks

**Comment by xXNiceYT** [comment]
Feature is added ty for request!
