### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jaylac2000** [CLADevs/Minion#27]
Is there a way in your next update to add /removeminion for ops ?

**Comment by jaylac2000** [comment]
so that it removes a minion. my spawn got griefed by them

**Comment by xXNiceYT** [comment]
I am sorry to hear that on next update might do it tmr I’ll add that feature so sorry

**Comment by jaylac2000** [comment]
It’s all good. I got a command blocker for other commands as well. Now only ppl with a specific perm can access it now. Even as an op without the perm you can’t use it

**Comment by xXNiceYT** [comment]
Done fixed on lastest.
