### ISSUE TITLE
BUG:  Players game crashes when they attempt to "Destroy, Link Chest, Upgrade"

### ISSUE THREAD

**Issue by ver24436** [CLADevs/Minion#39]
Players crash when they attempt to click on either "Destroy", "Link Chest", or "Upgrade" within the GUI.

`[Server thread/DEBUG]: Unhandled InventoryTransactionPacket received from Ver24436`

Minion v1.0.2 via >> https://poggit.pmmp.io/p/minion
PocketMine-MP v3.14.1  via >> https://github.com/pmmp/PocketMine-MP/releases/tag/3.14.1

**Comment by FluffyDev1** [comment]
This is a crash in new pocketmine update (mc 1.16).

**Comment by ver24436** [comment]
> This is a crash in new pocketmine update (mc 1.16).

So we have to wait for a patch on PMMP or does Minion Plugin need to be updated?

**Comment by xXNiceYT** [comment]
https://github.com/Muqsit/InvCrashFix Use this plugin to fix it it’s MCPE bug

**Comment by ver24436** [comment]
> https://github.com/Muqsit/InvCrashFix Use this plugin to fix it it’s MCPE bug

Thank you.
