### ISSUE TITLE
Bug In my opinion

### ISSUE THREAD

**Issue by deadbushmc** [CLADevs/Minion#46]
There is a problem if you have island and the minion will only work if you and minion are in the same chunk.
.__. kindly can u fix it please if minion and player are not in the same chunk it stops until players comes back to the same chunk as minion is.

**Comment by xXNiceYT** [comment]
hm I dont get what you mean?

**Comment by xXNiceYT** [comment]
there shouldn’t a chunk issue and I don’t think I can fix that

**Comment by xXNiceYT** [comment]
How may I reproduce this? I tried getting out of chunk and getting back in it was still mining.

**Comment by rjworks** [comment]
will it keep mining if the world is unloaded?

**Comment by xXNiceYT** [comment]
no I don’t think it would

**Comment by deadbushmc** [comment]
> no I don’t think it would



> How may I reproduce this? I tried getting out of chunk and getting back in it was still mining.

I didn't mean that if you out of chunk it will stop if you back to the chunk again then they will start again 😂
