### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by jaylac2000** [CLADevs/Minion#49]
![image](https://user-images.githubusercontent.com/53111006/92990253-d9900980-f4a8-11ea-90c9-7e49bac67941.png)

**Comment by xXNiceYT** [comment]
What version

**Comment by jaylac2000** [comment]
latest poggit release (dev 10 i think)

**Comment by deadbushmc** [comment]
> What version

yeah it spams string things soo much

**Comment by xXNiceYT** [comment]
Lastest version should be 29. You can download it at https://poggit.pmmp.io/ci/CLADevs/Minion/Minion
