### ISSUE TITLE
Stealing Bot by another player

### ISSUE THREAD

**Issue by eliassaliba12** [CLADevs/Minion#5]
The minion can be easily stealed if used on a server maybe add a owner to eash minion and the owner is the only one capable of upgrading and destroying the minion

**Comment by xXNiceYT** [comment]
Well i already got a idea so was gonna add them later

**Comment by eliassaliba12** [comment]
Ok

**Comment by benda95280** [comment]
It might be fun to defend/protect/hide your minion :)

Or

If you put it in a mine (big enough to hide some predefined minion, and
maybe hard to find), with 'unbreakable block', should be fun to see how
they will manage it.

Le lun. 2 sept. 2019 16:33, eliassaliba12 <notifications@github.com> a
écrit :

**Comment by eliassaliba12** [comment]
Well maybe he could add an option in configuratiom to either keep it like that or to be protected and have it owner
