### ISSUE TITLE
Suggestion to Use InvMenu Virion

### ISSUE THREAD

**Issue by ghost** [CLADevs/Minion#53]
Currently your using just a hooper, like the actual block as the fake inventory. Issue with this is that well you can see the hopper and the hopper can actually break a block if there was a block where the hopper was “spawned in”. Besides that I honestly love this plugin. If your able to do this that would be amazing because I have tried and it failed. Have a great day!!

**Comment by xXNiceYT** [comment]
Well what do u want me to do, it shouldn’t effect ur real block it just changes it temporarily then changes back to their normal block after closing inv. If it doesn’t do this I forgot smth prob

**Comment by ghost** [comment]
Thank you for replying I wasn’t expecting such a fast reply I would have responded sooner. So maybe what can be done is that I can modify this plugin with your permission to make it use InvMenu Virion and you can fix what mistakes I make when adding it in. I am bound to make some mistakes, I am kinda new at this. This way you wouldn’t have to add in the Virion. I would be happy to help since I requested this 😀.

**Comment by xXNiceYT** [comment]
I would like this plugin to support lastest InvMenu sorry
