### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by deadbushmc** [CLADevs/Minion#54]
Ok so I have a friend who needs a dev for minion plugin since you are a minion plugin dev for pmmp. dm me on discord my username is DeadBush#8605 ill tell you the requirements we can pay you upto 100+ USD.
we wants different kinds of minion

**Comment by SinkerzGod** [comment]
What are the requirements?

**Comment by sink-github** [comment]
> Ok so I have a friend who needs a dev for minion plugin since you are a minion plugin dev for pmmp. dm me on discord my username is DeadBush#8605 ill tell you the requirements we can pay you upto 100+ USD.
> we wants different kinds of minion

What are the requirements?
